{{- if $.Values.features.frontend.enabled }}
{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.frontendFullname" . }}
  annotations:
    {{- if .Values.shared.config.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "secret.basicAuthName" . }}
    {{- end }}
    {{- if .Values.shared.config.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.shared.config.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.shared.config.tls.host }}
      secretName: {{ .Values.shared.config.tls.secretName }}
  {{- end }}
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host.name }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.host.path }}
            pathType: {{ .Values.frontend.ingress.host.pathType }}
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.ingress.host.port }}
{{- end }}
{{- end }}
