apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    name: backend
    targetPort: {{ .Values.backend.service.port }}
  {{- if .Values.features.mcp.enabled }}
  - port: {{ .Values.backend.mcp.port }}
    targetPort: {{ .Values.backend.mcp.port }}
    name: mcp
  {{- end }}
  selector:
    app: {{ .Values.backend.name }}
